# Generated by Django 4.0.3 on 2022-03-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url_to_image',
            field=models.ImageField(default='image.png', upload_to='images/'),
        ),
    ]
